/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ankledot (https://sketchfab.com/Ankledot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/headphones-skullcandy-crusher-wireless-4e902017e4624547b440da0a6658a689
Title: Headphones Skullcandy Crusher Wireless
*/

import * as THREE from "three";
import React, { useEffect, useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import gsap from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    Skullcandy_Crusher_M_Skullcandy_Crusher_0: THREE.Mesh;
  };
  materials: {
    M_Skullcandy_Crusher: THREE.MeshStandardMaterial;
  };
};
type HeadphoneProps = {};

export function Headphone(props: HeadphoneProps) {
  const gsapRef = useRef<THREE.Group>(null);
  const headphoneEmission = useTexture(
    "/textures/M_Skullcandy_Crusher_emissive.png"
  );
  const headphoneRoughness = useTexture(
    "/textures/M_Skullcandy_Crusher_normal.png"
  );
  const { nodes } = useGLTF("/scene.gltf") as unknown as GLTFResult;
  const headphoneMaterials = useMemo(() => {
    const material = new THREE.MeshStandardMaterial({
      map: headphoneEmission,
      bumpMap: headphoneRoughness,
      roughnessMap: headphoneRoughness,
      metalness: 0.3,
      bumpScale: 0.8,
      roughness: 1,
    });
    if (headphoneRoughness) {
      headphoneRoughness.anisotropy = 0.8;
      headphoneRoughness.needsUpdate = true;
    }
    return material;
  }, [headphoneRoughness, headphoneEmission]);

  useEffect(() => {
    if (gsapRef.current) {
      gsap.to(gsapRef.current.rotation, {
        y: Math.PI * 2,
        duration: 30,
        ease: "none",
        repeat: -1,
      });
    }
  }, []);
  return (
    <group ref={gsapRef} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="651a5fb240664e20bd234720aa4694e1fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="RootNode">
              <group
                name="Skullcandy_Crusher"
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.4}
              >
                <mesh
                  name="Skullcandy_Crusher_M_Skullcandy_Crusher_0"
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Skullcandy_Crusher_M_Skullcandy_Crusher_0.geometry
                  }
                  material={headphoneMaterials}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
